apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sf-nada-dialog
  namespace: team-dialog
  labels:
    team: team-dialog
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  resources:
    limits:
      memory: 3Gi
    requests:
      cpu: 10m
      memory: 1Gi
  ingresses:
    - "https://sf-nada-dialog.intern.nav.no"
  envFrom:
    - secret: sf-nada-prod
  gcp:
     bigQueryDatasets:
      - name: arbeidsgiver_aktivitet
        permission: READWRITE
      - name: arbeidsgiver_diverse
        permission: READWRITE
      - name: arbeidsgiver_data
        permission: READWRITE
  accessPolicy:
    outbound:
      external:
        - host: login.salesforce.com
        - host: navdialog.my.salesforce.com
  env:
    - name: POST_TO_BIGQUERY
      value: 'true'
    - name: RUN_SESSION_ON_STARTUP
      value: 'true'
    - name: FETCH_ALL_RECORDS
      value: 'false'
    - name: EXCLUDE_TABLES
      value: ''
    - name: MAPDEF_FILE
      value: '/mapdef/prod.json'
    - name: SF_TOKENHOST
      value: 'https://login.salesforce.com'
    - name: SF_QUERY_BASE
      value : '/services/data/v57.0/query?q='
    - name: DEPLOY_CLUSTER
      value: {{ DEPLOY_CLUSTER }}